# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-05 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_statues',
            new_name='post_status',
        ),
    ]
