# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-05 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191005_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostInProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 0), (1, 1)])),
                ('company_name', models.CharField(default='not_filled', max_length=500)),
                ('requirements', models.CharField(default='not_filled', max_length=10000)),
                ('ceil', models.IntegerField(default=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='ceil_done',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ceil_progress',
        ),
        migrations.AddField(
            model_name='post',
            name='ceil',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='postinprocess',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Post'),
        ),
    ]
