# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-05 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_post_statues'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ceil',
            field=models.IntegerField(default=100),
        ),
    ]
