# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-05 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_post_like_cnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=500),
        ),
    ]
