# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-05 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191005_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='post',
        ),
        migrations.AddField(
            model_name='report',
            name='post_in_process',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.PostInProcess'),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_status',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=1),
        ),
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(default=None, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='report',
            name='text',
            field=models.CharField(default='not_filled', max_length=500),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(default='not_filled', max_length=500),
        ),
        migrations.AlterField(
            model_name='report',
            name='youtube_link',
            field=models.CharField(default='not-filled.com', max_length=500),
        ),
    ]
