# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-06 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191005_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='postinprocess',
            name='repost_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='like_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postinprocess',
            name='status',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)]),
        ),
    ]
