# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-06 00:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191006_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='postinprocess',
            name='deadline',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
