# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-06 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_postinprocess_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='postinprocess',
            name='author',
            field=models.CharField(default='not_filled', max_length=200),
        ),
    ]
