# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-06 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_postinprocess_percentage_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='postinprocess',
            name='company_logo',
            field=models.ImageField(default=None, null=True, upload_to=b''),
        ),
    ]
